version: "3.8"
services:
  client:
    build: ./client
    command: yarn dev-server
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
    depends_on:
      - server 
  server:
    build: ./server
    command: yarn start:dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db 
      DB_USER: root
      DB_NAME: jupiter_development_db
      DB_PASSWORD: password
      DB_PORT: 3306
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - ./server/node_modules:/usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jupiter_development_db
    ports:
      - "3306:3306"
    volumes:
      - jupiter_development_db:/var/lib/mysql
volumes:
  jupiter_development_db:
